version: '3.4'

networks:
  db-access:
    driver: bridge 

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - db-access
    volumes:
      - "${MYSQL_DATA_SRC}:/var/lib/mysql"

  odata:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - mysqldb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERT_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings: DefaultConnection="Host=mysqldb;Port=5432;Database=${MYSQL_DATABASE};username=${MYSQL_USER};password=${MYSQL_PASSWORD}"
    ports:
      - 80:80
      - 443:443
    networks:
      - db-access
    volumes:
      - ~/.aspnet/https:/https:ro
